name: haber_app
description: Bir Flutter projesi için başlangıç ​​noktasıdır. Uygulama, haberleri görsel olarak sunan bir mobil uygulamayı içermektedir.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: '>=2.10.5 <3.0.0'
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  video_player: ^2.7.0
  dio: ^5.3.2
  url_launcher: ^6.1.12
  flutter_launcher_icons: ^0.13.1 

dev_dependencies:
  flutter_test:
    sdk: '>=0.10.5 <3.0.0'
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
