name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Flutter SDK
        run: |
          git clone --branch 2.10.5 --depth 1 https://github.com/flutter/flutter.git $HOME/flutter
          export PATH="$HOME/flutter/bin:$PATH"
          flutter config --no-analytics

      - name: Set up Flutter
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get # Use `flutter pub get` for Flutter projects

      - name: Analyze project source
        run: dart analyze # Use `dart analyze` for Dart projects (non-Flutter)

      - name: Run tests
        run: dart test # Use `dart test` for Dart projects (non-Flutter)
