name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Use the official Flutter setup action
        with:
          flutter-version: '2.x' # Replace with the desired Flutter version

      - name: Install dependencies
        run: flutter pub get # Use `flutter pub get` for Flutter projects

      - name: Analyze project source
        run: dart analyze # Use `dart analyze` for Dart projects (non-Flutter)

      - name: Run tests
        run: dart test # Use `dart test` for Dart projects (non-Flutter)
